// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"N_StartFullscreen","status":false,"description":"Start game in fullscreen","parameters":{"textExit":"Exit","textToDesktop":"To Desktop"}},
{"name":"TextPicture","status":true,"description":"Displays text as a picture.","parameters":{}}
];
